export const SELLER_VERIFICATION_MAX_IMAGE_SIZE_MB = 30;

export const SELLER_VERIFICATION_MAX_IMAGE_SIZE_BYTES =
  SELLER_VERIFICATION_MAX_IMAGE_SIZE_MB * 1024 * 1024;

export const SELLER_VERIFICATION_MAX_IMAGE_SIZE_LABEL = `${SELLER_VERIFICATION_MAX_IMAGE_SIZE_MB}MB`;

export const SELLER_VERIFICATION_UPLOAD_HELPER_TEXT = `Máx. ${SELLER_VERIFICATION_MAX_IMAGE_SIZE_LABEL} por imagem`;

/** Altura do preview no formulário (compacto para modal). */
export const SELLER_VERIFICATION_DOC_PREVIEW_HEIGHT = 72;
